title: Quiz Masterz
description: Documentation for Quiz Masterz Project
theme: just-the-docs

# Enable Mermaid diagram support
mermaid:
  # Version of mermaid library
  version: "9.1.3"
  # Put any additional configuration here